name: .NET Core

on: [push, pull_request]

jobs:
  dotnet:
    name: ${{ matrix.framework-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework-version: [net6.0, netcoreapp3.1]

    steps:
      - uses: actions/checkout@master

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Tests
        run: dotnet test -c Release -f ${{ matrix.framework-version }}
